# Generated by Django 4.0 on 2023-11-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users_photo/3-4.jpg', null=True, upload_to='users_photos/'),
        ),
    ]
